version: '3'
services:
  web:
    image: yourbr0ther/pokemon-smile:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - /mnt/user/appdata/pokemon-smile/static:/app/static
      - /mnt/user/appdata/pokemon-smile/templates:/app/templates
      - /mnt/user/appdata/pokemon-smile/data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /mnt/user/appdata/pokemon-smile/mongodb:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
